### PR TITLE
Bump runtime-version to 22.08

### PR DESCRIPTION
**Pull request by nabeelcodes**

### CODE REVIEW

**Comment by ids1024** [comment]
```
warning: spurious network error (2 tries remaining): failed to resolve address for github.com: Temporary failure in name resolution; class=Net (12)
warning: spurious network error (1 tries remaining): failed to resolve address for github.com: Temporary failure in name resolution; class=Net (12)
error: failed to get `dbus-udisks2` as a dependency of package `popsicle_gtk v1.3.0 (/run/build/popsicle/gtk)`
```

Fun, I love when CI builds fail due to spurious network errors. /s

Presumably it would otherwise build. I guess it's correct not to depend on 20.08 if that's EOL. Though I'm not sure what impact runtime version has on a Flatpak package's ability to run on old distros? (I believe things like glibc can have a minimum kernel version requirement, etc.)

https://gitlab.com/freedesktop-sdk/freedesktop-sdk#usage still shows `"runtime-version": "20.08"`. Presumably that should be updated.

**Comment by cassidyjames** [comment]
> https://gitlab.com/freedesktop-sdk/freedesktop-sdk#usage still shows `"runtime-version": "20.08"`. Presumably that should be updated.

Good catch, merge requested https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/9832

**Comment by cassidyjames** [comment]
>I'm not sure what impact runtime version has on a Flatpak package's ability to run on old distros?

As far as I'm aware, a newer runtime will run just fine on any distro supported by Flatpak. In practice, I am happy to test on an old Pop!_OS release in a VM if you'd like.

Also for anyone lurking, I'm working on adding a Flatpak manifest and some Flatpak-adjacent improvements directly upstream with the ultimate goals of making it easier to contribute plus getting a new release for Flathub. :wink:

**Comment by ids1024** [comment]
> As far as I'm aware, a newer runtime will run just fine on any distro supported by Flatpak. 

Yeah, probably. I'm just not entirely sure how the details related to backwards compatibility work with Flatpak. For AppImage, certain libraries are not bundled, so it's necessary to have compatible versions of those. (And it's conventional to build AppImages on an old distro to improve compatibility.) I guess with Flatpak it even bundles glibc? Then I believe things like glibc may require a certain kernel version, but perhaps it's ancient enough to not be a problem.

**Comment by cassidyjames** [comment]
>For AppImage, certain libraries are not bundled, so it's necessary to have compatible versions of those. (And it's conventional to build AppImages on an old distro to improve compatibility.) 

Yeah this is a common pain point with AppImage, and something _as far as I know_ that the design of Flatpak avoids. But unfortunately I don't know the specifics.

Anyway, here's a screenshot of Popsicle built against 22.08 running on Ubuntu 16.04. :joy: 

Screenshot from 2022-09-26 22-17-04

**Comment by ids1024** [comment]
I need to research more about how the runtimes and sandboxing work in Flatpak... but in any case, running on Ubuntu 16.04 seems satisfactory enough. :+1:

**Comment by ids1024** [comment]
Hm, the build still fails after I told it to run again...

**Comment by bilelmoussaoui** [comment]
The build commands should probably pass --offline to cargo

**Comment by ids1024** [comment]
Build seems to be working now after updating to the new Popsicle release and regenerating `generated-sources.json`: https://github.com/flathub/com.system76.Popsicle/pull/8.

**Pull request closed without merging**
